'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoComposto", [Namespace]:="http://schemas.datacontract.org/2004/07/Wcf_Validacao"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoComposto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValorBooleanField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValorDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValorStringField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValorBoolean() As Boolean
            Get
                Return Me.ValorBooleanField
            End Get
            Set
                If (Me.ValorBooleanField.Equals(value) <> true) Then
                    Me.ValorBooleanField = value
                    Me.RaisePropertyChanged("ValorBoolean")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValorDate() As Date
            Get
                Return Me.ValorDateField
            End Get
            Set
                If (Me.ValorDateField.Equals(value) <> true) Then
                    Me.ValorDateField = value
                    Me.RaisePropertyChanged("ValorDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValorString() As String
            Get
                Return Me.ValorStringField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValorStringField, value) <> true) Then
                    Me.ValorStringField = value
                    Me.RaisePropertyChanged("ValorString")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IValidacao")>  _
    Public Interface IValidacao
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ObterDados", ReplyAction:="http://tempuri.org/IValidacao/ObterDadosResponse")>  _
        Function ObterDados(ByVal valor As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ObterDadosUsandoContratoDeDados", ReplyAction:="http://tempuri.org/IValidacao/ObterDadosUsandoContratoDeDadosResponse")>  _
        Function ObterDadosUsandoContratoDeDados(ByVal composicao As ServiceReference1.TipoComposto) As ServiceReference1.TipoComposto
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ValidarNomesUsuarios", ReplyAction:="http://tempuri.org/IValidacao/ValidarNomesUsuariosResponse")>  _
        Function ValidarNomesUsuarios(ByVal nomeUsuario As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ValidarNumerosTelefonicos", ReplyAction:="http://tempuri.org/IValidacao/ValidarNumerosTelefonicosResponse")>  _
        Function ValidarNumerosTelefonicos(ByVal numeroTelefonico As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ValidarEmail", ReplyAction:="http://tempuri.org/IValidacao/ValidarEmailResponse")>  _
        Function ValidarEmail(ByVal email As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ValidarCodigosPostais", ReplyAction:="http://tempuri.org/IValidacao/ValidarCodigosPostaisResponse")>  _
        Function ValidarCodigosPostais(ByVal codigoPostal As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ValidarEnderecosIP", ReplyAction:="http://tempuri.org/IValidacao/ValidarEnderecosIPResponse")>  _
        Function ValidarEnderecosIP(ByVal EnderecoIP As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ValidarCoresHexadecimais", ReplyAction:="http://tempuri.org/IValidacao/ValidarCoresHexadecimaisResponse")>  _
        Function ValidarCoresHexadecimais(ByVal corHexadecimal As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ValidarComentariosMultiLinha", ReplyAction:="http://tempuri.org/IValidacao/ValidarComentariosMultiLinhaResponse")>  _
        Function ValidarComentariosMultiLinha(ByVal comentarioMultiLinha As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IValidacao/ValidarDatas", ReplyAction:="http://tempuri.org/IValidacao/ValidarDatasResponse")>  _
        Function ValidarDatas(ByVal data As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IValidacaoChannel
        Inherits ServiceReference1.IValidacao, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ValidacaoClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IValidacao)
        Implements ServiceReference1.IValidacao
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObterDados(ByVal valor As Integer) As String Implements ServiceReference1.IValidacao.ObterDados
            Return MyBase.Channel.ObterDados(valor)
        End Function
        
        Public Function ObterDadosUsandoContratoDeDados(ByVal composicao As ServiceReference1.TipoComposto) As ServiceReference1.TipoComposto Implements ServiceReference1.IValidacao.ObterDadosUsandoContratoDeDados
            Return MyBase.Channel.ObterDadosUsandoContratoDeDados(composicao)
        End Function
        
        Public Function ValidarNomesUsuarios(ByVal nomeUsuario As String) As Boolean Implements ServiceReference1.IValidacao.ValidarNomesUsuarios
            Return MyBase.Channel.ValidarNomesUsuarios(nomeUsuario)
        End Function
        
        Public Function ValidarNumerosTelefonicos(ByVal numeroTelefonico As String) As Boolean Implements ServiceReference1.IValidacao.ValidarNumerosTelefonicos
            Return MyBase.Channel.ValidarNumerosTelefonicos(numeroTelefonico)
        End Function
        
        Public Function ValidarEmail(ByVal email As String) As Boolean Implements ServiceReference1.IValidacao.ValidarEmail
            Return MyBase.Channel.ValidarEmail(email)
        End Function
        
        Public Function ValidarCodigosPostais(ByVal codigoPostal As String) As Boolean Implements ServiceReference1.IValidacao.ValidarCodigosPostais
            Return MyBase.Channel.ValidarCodigosPostais(codigoPostal)
        End Function
        
        Public Function ValidarEnderecosIP(ByVal EnderecoIP As String) As Boolean Implements ServiceReference1.IValidacao.ValidarEnderecosIP
            Return MyBase.Channel.ValidarEnderecosIP(EnderecoIP)
        End Function
        
        Public Function ValidarCoresHexadecimais(ByVal corHexadecimal As String) As Boolean Implements ServiceReference1.IValidacao.ValidarCoresHexadecimais
            Return MyBase.Channel.ValidarCoresHexadecimais(corHexadecimal)
        End Function
        
        Public Function ValidarComentariosMultiLinha(ByVal comentarioMultiLinha As String) As Boolean Implements ServiceReference1.IValidacao.ValidarComentariosMultiLinha
            Return MyBase.Channel.ValidarComentariosMultiLinha(comentarioMultiLinha)
        End Function
        
        Public Function ValidarDatas(ByVal data As String) As Boolean Implements ServiceReference1.IValidacao.ValidarDatas
            Return MyBase.Channel.ValidarDatas(data)
        End Function
    End Class
End Namespace
